name: Build parquet_utils

on:
  push:
    paths:
      - 'parquet_utils/**'
      - '.github/workflows/test_parquet_utils.yml'
  pull_request:
    paths:
      - 'parquet_utils/**'
      - '.github/workflows/test_parquet_utils.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake git

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '2d6a6cf3ac9a7cc93942c3d289a2f9c661a6f4a7'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Install vcpkg packages
        run: |
          ${GITHUB_WORKSPACE}/vcpkg/vcpkg install --manifest


      - name: Configure CMake with vcpkg
        run: |
          cmake -S . -B build \
                -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build parquet_utils
        run: cmake --build build --config Release
