name: Build parquet_utils

on:
  workflow_dispatch:
  push:
    paths:
      - 'parquet_utils/**'
      - '.github/workflows/build_parquet_utils.yml'
  pull_request:
    paths:
      - 'parquet_utils/**'
      - '.github/workflows/build_parquet_utils.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@v3.30.1

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure (CMakePresets)
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'

      - name: Build parquet_utils
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'default-build'
