name: Build parquet_utils

on:
  push:
    paths:
      - 'parquet_utils/**'
      - '.github/workflows/test_parquet_utils.yml'
  pull_request:
    paths:
      - 'parquet_utils/**'
      - '.github/workflows/test_parquet_utils.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
         vcpkgGitCommitId: '2d6a6cf3ac9a7cc93942c3d289a2f9c661a6f4a7'

      - name: Install dependencies (manifest mode)
        run: ${{ env.VCPKG_ROOT }}/vcpkg install

      - name: Configure CMake
        run: |
         cmake -S . -B build \
         -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \
         -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

